
server:
  port: 9090
spring:
  application:
    name: service-provider2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qfssm?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

curcka:
  client:
    service-url:
      defaultZone: http://localhost:8761/euraka

mybatis:
  type-aliases-package: com.qf.j1906.pojo
  mapper-locations: classpath*:mapping/*.xml

