
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
client:
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

  registry-with-eureka: false
  fetch-registry: false

